// Mock API service for the demo

export const cleanText = async (rawText) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(`[Cleaned] ${rawText}\n\n(This text has been cleaned by the AI service to remove filler words and improve readability.)`);
    }, 1500);
  });
};

export const generateSummary = async (cleanedText) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        topic: "General Conversation",
        summary: "This is a summary generated by Fittcore based on the conversation. The speakers discussed various topics including mobile app development and AI integration.",
        keyPoints: [
          "User wants a mobile app for STT.",
          "App needs to clean text using AI.",
          "App needs to send text to Fittcore for summary.",
          "Supports Thai/English mix."
        ]
      });
    }, 2000);
  });
};
