# ==================== FITT BSA PLATFORM WEB - SANDBOX/DEVELOPMENT ====================
# Deploy to Cloud Run (asia-southeast1 region)
# Firestore Database: fittsuperapp-dev
# Environment: Sandbox/Development

steps:
  # ==================== BUILD ====================
  - name: "gcr.io/cloud-builders/docker"
    id: "build-sandbox"
    dir: "platform-web"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIRESTORE_DATABASE_ID=fittsuperapp-dev"
      - "--build-arg"
      - "FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "--build-arg"
      - "FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}"
      - "--build-arg"
      - "FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}"
      - "--build-arg"
      - "RESEND_API_KEY=${_RESEND_API_KEY}"
      - "--build-arg"
      - "FROM_EMAIL=${_FROM_EMAIL}"
      - "--build-arg"
      - "DMAIL_API_KEY=${_DMAIL_API_KEY}"
      - "-t"
      - "gcr.io/$PROJECT_ID/platform-web-dev:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/platform-web-dev:latest"
      - "-f"
      - "Dockerfile"
      - "."

  # ==================== PUSH IMAGE ====================
  - name: "gcr.io/cloud-builders/docker"
    id: "push-sandbox-sha"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/platform-web-dev:$COMMIT_SHA"
    waitFor: ["build-sandbox"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-sandbox-latest"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/platform-web-dev:latest"
    waitFor: ["build-sandbox"]

  # ==================== DEPLOY TO CLOUD RUN ====================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-sandbox"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "fittbsa-admin-web-dev"
      - "--image"
      - "gcr.io/$PROJECT_ID/platform-web-dev:$COMMIT_SHA"
      - "--region"
      - "asia-southeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--max-instances"
      - "2"
      - "--min-instances"
      - "0"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID},NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID},NEXT_PUBLIC_FIRESTORE_DATABASE_ID=fittsuperapp-dev,FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY},RESEND_API_KEY=${_RESEND_API_KEY},FROM_EMAIL=${_FROM_EMAIL},DMAIL_API_KEY=${_DMAIL_API_KEY}"
      - "--tag"
      - "sandbox"
    waitFor: ["push-sandbox-sha"]

# ==================== IMAGES ====================
images:
  - "gcr.io/$PROJECT_ID/platform-web-dev:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/platform-web-dev:latest"

# ==================== BUILD OPTIONS ====================
options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"

# ==================== SUBSTITUTIONS ====================
# ⚠️ Configuration Instructions:
# 1. Go to Google Cloud Console > Cloud Build > Triggers
# 2. Create or edit your trigger
# 3. Add these substitution variables with actual values:
substitutions:
  _FIREBASE_API_KEY: "SET_IN_CLOUD_BUILD_TRIGGER"
  _FIREBASE_AUTH_DOMAIN: "fittbsa.firebaseapp.com"
  _FIREBASE_PROJECT_ID: "fittbsa"
  _FIREBASE_STORAGE_BUCKET: "fittbsa.firebasestorage.app"
  _FIREBASE_MESSAGING_SENDER_ID: "1095128507689"
  _FIREBASE_APP_ID: "1:1095128507689:web:ab0d0fbcdd9723f17f4338"
  _FIREBASE_MEASUREMENT_ID: "G-4HZ4296L6F"
  _FIREBASE_CLIENT_EMAIL: "SET_IN_CLOUD_BUILD_TRIGGER"
  _FIREBASE_PRIVATE_KEY: "SET_IN_CLOUD_BUILD_TRIGGER"
  _RESEND_API_KEY: "SET_IN_CLOUD_BUILD_TRIGGER"
  _FROM_EMAIL: "onboarding@resend.dev"
  _DMAIL_API_KEY: "SET_IN_CLOUD_BUILD_TRIGGER"
